name: main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:
    types: rebuild

jobs:
  tii-deb-build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout navigation
        uses: actions/checkout@v2
        with:
          path: navigation

      - name: Checkout ci-scripts
        uses: actions/checkout@v2
        with:
          repository: tiiuae/fogsw-ci-scripts
          path: fogsw-ci-scripts

      # Run docker build
      - name: Run fog-core docker build
        run: |
          set -eux
          mkdir bin
          pushd fogsw-ci-scripts
          export ROS=1
          ./generate_deb.sh ../navigation ../bin/
          popd

      - name: Install jfrog CLI tool
        env:
          JFROG_CLI_URL: https://artifactory.ssrc.fi/artifactory/gen-public-local/tools/jfrog/jfrog-1.45.2.tar.gz
        if: github.event_name == 'push' || github.event.action == 'rebuild'
        run: |
          set -exu
          mkdir -p "$GITHUB_WORKSPACE/.jfrog/bin"
          curl -L "$JFROG_CLI_URL" -o "$GITHUB_WORKSPACE/.jfrog/jfrog.tar.gz"
          tar -C "$GITHUB_WORKSPACE/.jfrog/bin" -zxf "$GITHUB_WORKSPACE/.jfrog/jfrog.tar.gz"
          echo "$GITHUB_WORKSPACE/.jfrog/bin" >> "$GITHUB_PATH"
          echo "JFROG_CLI_HOME_DIR=$GITHUB_WORKSPACE/.jfrog" >> "$GITHUB_ENV"

      - name: Upload to Artifactory
        env:
          ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
          ARTIFACTORY_REPO: debian-public-local
          DISTRIBUTION: focal
          COMPONENT: fog-sw
          ARCHITECTURE: amd64
          BUILD_NAME: navigation
          CI: true
        if: github.event_name == 'push' || github.event.action == 'rebuild'
        run: |
          set -exu
          jfrog rt c import "$ARTIFACTORY_TOKEN"
          jfrog rt ping
          pkg=$(find bin -name 'ros-foxy-navigation*.deb')
          build_id="$GITHUB_SHA-$GITHUB_RUN_NUMBER"
          jfrog rt u --deb "$DISTRIBUTION/$COMPONENT/$ARCHITECTURE" \
                     --target-props COMMIT="$GITHUB_SHA" \
                     --build-name "$BUILD_NAME" \
                     --build-number "$build_id" \
                     "$pkg" \
                     "$ARTIFACTORY_REPO"
          jfrog rt build-publish "$BUILD_NAME" "$build_id"
          jfrog rt bpr "$BUILD_NAME" "$build_id" "$ARTIFACTORY_REPO" \
                       --status dev \
                       --comment "development build"
